# services:
#   - type: web
#     name: license-plate-detector
#     runtime: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: gunicorn app:app
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.10

services:
  - type: web
    name: license-plate-detector
    runtime: python
    pythonVersion: 3.10
    buildCommand: "pip install --upgrade pip && pip install --only-binary :all: -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120 --workers 2 --bind 0.0.0.0:$PORT"
    memoryMB: 1024
